[package]
name = "halo2deeplearning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/zcash/halo2.git", rev = "a898d65ae3ad3d41987666f6a03cfc15edae01c4"}
#halo2_proofs = { path = "../halo2/halo2_proofs" }
nalgebra = "0.31"
pasta_curves = "0.4"
rand = "0.8"
mnist = "0.5"
ndarray = "0.15"
tensorflow = {version = "0.18.0", features = ["eager"], optional = true }
plotters = { version = "0.3.0", optional = true }

[features]
dev-graph = ["halo2_proofs/dev-graph", "plotters"]
tensorflow = ["dep:tensorflow"]


